### ISSUE TITLE
some twitter errors do not return json

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#10]
<pre>

[Thu Nov 11 06:25:01 2010] [error] Traceback (most recent call last):
[Thu Nov 11 06:25:01 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/controllers/send.py", line 116, in send
[Thu Nov 11 06:25:01 2010] [error]     result, error = provider.api(acct).sendmessage(message, args)
[Thu Nov 11 06:25:01 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/twitter_.py", line 162, in sendmessage
[Thu Nov 11 06:25:01 2010] [error]     details = json.load(exc.e)
[Thu Nov 11 06:25:01 2010] [error]   File "/usr/lib64/python2.6/json/__init__.py", line 267, in load
[Thu Nov 11 06:25:01 2010] [error]     parse_constant=parse_constant, **kw)
[Thu Nov 11 06:25:01 2010] [error]   File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
[Thu Nov 11 06:25:01 2010] [error]     return _default_decoder.decode(s)
[Thu Nov 11 06:25:01 2010] [error]   File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
[Thu Nov 11 06:25:01 2010] [error]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[Thu Nov 11 06:25:01 2010] [error]   File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
[Thu Nov 11 06:25:01 2010] [error]     raise ValueError("No JSON object could be decoded")
[Thu Nov 11 06:25:01 2010] [error] ValueError: No JSON object could be decoded

</pre>

**Comment by mixedpuppy** [comment]
non-json errors handled better change f2c5939277bba4c19894
