### ISSUE TITLE
no auth code received

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#11]
<pre>

[Thu Nov 11 05:41:06 2010] [error] Traceback (most recent call last):
[Thu Nov 11 05:41:06 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/controllers/account.py", line 119, in verify
[Thu Nov 11 05:41:06 2010] [error]     user = auth.verify()
[Thu Nov 11 05:41:06 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/base.py", line 119, in verify
[Thu Nov 11 05:41:06 2010] [error]     raise Exception("No oauth code received")
[Thu Nov 11 05:41:06 2010] [error] Exception: No oauth code received

</pre>

**Comment by mixedpuppy** [comment]
fixed (better error message added) 3e86e0482bd3ff91f578
