### ISSUE TITLE
better error result for cancelling oauth

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#12]
<pre>

[Thu Nov 11 07:53:51 2010] [error] Traceback (most recent call last):
[Thu Nov 11 07:53:51 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/controllers/account.py", line 119, in verify
[Thu Nov 11 07:53:51 2010] [error]     user = auth.verify()
[Thu Nov 11 07:53:51 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/openidconsumer.py", line 324, in verify
[Thu Nov 11 07:53:51 2010] [error]     raise Exception("consumer canceled: "+info.message)
[Thu Nov 11 07:53:51 2010] [error] AttributeError: 'CancelResponse' object has no attribute 'message'

</pre>

**Comment by mixedpuppy** [comment]
fixed with better error messages 3e86e0482bd3ff91f578
