### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument '_warn_on_bytestring'

### ISSUE THREAD

**Issue by arthurzenika** [mozilla/f1#15]
Followed the instructions on the front page and got this : 

$ paster serve --reload development.ini
Starting subprocess with file monitor
Traceback (most recent call last):
  File "/home/arthur/local/f1/env/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.3', 'console_scripts', 'paster')()
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 84, in run
    invoke(command, command_name, options, args[1:])
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 123, in invoke
    exit_code = runner.run(args)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 218, in run
    result = self.command()
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/serve.py", line 276, in command
    relative_to=base, global_conf=vars)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/serve.py", line 313, in loadapp
    *_kw)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 204, in loadapp
    return loadobj(APP, uri, name=name, *_kw)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 225, in loadobj
    return context.create()
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 625, in create
    return self.object_type.invoke(self)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 177, in invoke
    next_app = context.next_context.create()
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 625, in create
    return self.object_type.invoke(self)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 177, in invoke
    next_app = context.next_context.create()
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 625, in create
    return self.object_type.invoke(self)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 108, in invoke
    *_context.local_conf)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/util/fixtypeerror.py", line 57, in fix_call
    val = callable(_args, *_kw)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/Paste-1.7.3.1-py2.6.egg/paste/urlmap.py", line 24, in urlmap_factory
    app = loader.get_app(app_name, global_conf=global_conf)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 297, in get_app
    name=name, global_conf=global_conf).create()
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 309, in app_context
    APP, name=name, global_conf=global_conf)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 409, in get_context
    section)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 431, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 361, in get_context
    global_conf=global_conf)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 248, in loadcontext
    global_conf=global_conf)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 285, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 561, in get_context
    object_type, name=name)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 587, in find_egg_entry_point
    possible.append((entry.load(), protocol, entry.name))
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/distribute-0.6.10-py2.6.egg/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['**name**'])
  File "/home/arthur/local/f1/linkdrop/config/middleware.py", line 34, in <module>
    from linkdrop.config.environment import load_environment
  File "/home/arthur/local/f1/linkdrop/config/environment.py", line 38, in <module>
    import linkdrop.lib.helpers
  File "/home/arthur/local/f1/linkdrop/lib/helpers.py", line 39, in <module>
    from linkdrop.model.meta import Session
  File "/home/arthur/local/f1/linkdrop/model/**init**.py", line 26, in <module>
    from linkdrop.model.account import Account
  File "/home/arthur/local/f1/linkdrop/model/account.py", line 34, in <module>
    class Account(JsonExpandoMixin, SerializerMixin, Base):
  File "/home/arthur/local/f1/linkdrop/model/account.py", line 40, in Account
    key = Column(RDUnicode(64), index=True)
  File "/home/arthur/local/f1/linkdrop/model/types.py", line 40, in **init**
    super(RDUnicode, self).**init**(length=length, *_kwargs)
  File "/home/arthur/local/f1/env/lib/python2.6/site-packages/SQLAlchemy-0.5.8-py2.6.egg/sqlalchemy/types.py", line 549, in **init**
    super(Unicode, self).**init**(length=length, **kwargs)

**Comment by mixedpuppy** [comment]
Try a later version of SQLAlchemy.  You should be able to "easy_install -U sqlalchemy" to install 0.6.x.

**Comment by clarkbw** [comment]
let us know if there's still a problem
