### ISSUE TITLE
f1 error when sharing via email but 'to' address is not specified.

### ISSUE THREAD

**Issue by mhammond** [mozilla/f1#57]
Attempt to share a link via email but leave the 'to' field blank.  F1 responds with a "f1 goofed up" error and the log will contain the error below:

<pre>
12:37:44,296 ERROR [linkdrop.lib.helpers] [worker 5] <function send at 0x03555430>((<linkdrop.controllers.send.SendController object at 0x037EAF30>,), {}) failed
Traceback (most recent call last):
  File "O:\src\mm\f1\work\linkdrop\lib\helpers.py", line 128, in json_exception_response
    return func(*args, **kwargs)
  File "O:\src\mm\f1\work\linkdrop\controllers\send.py", line 175, in send
    result, error = provider.api(acct).sendmessage(message, args)
  File "O:\src\mm\f1\work\linkdrop\lib\oauth\google_.py", line 255, in sendmessage
    to_ = options['to']
  File "o:\src\python-2.6-svn\lib\site-packages\webob-0.9.8-py2.6.egg\webob\multidict.py", line 315,
 in __getitem__
    return self._decode_value(self.multi.__getitem__(self._encode_key(key)))
  File "o:\src\python-2.6-svn\lib\site-packages\webob-0.9.8-py2.6.egg\webob\multidict.py", line 79,
in __getitem__
    raise KeyError(key)
KeyError: 'to'
</pre>

**Comment by mixedpuppy** [comment]
improved error handling of recipient address, fixed
