### ISSUE TITLE
errors in openid are not handled well in the ui

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#70]
given a socket timeout, the oauth panel will spin forever.  the exception below can be faked to recreate the issue.

<pre>
Traceback (most recent call last):
  File "/Users/shanec/mofo/f1/linkdrop/controllers/account.py", line 119, in verify
    user = auth.verify()
  File "/Users/shanec/mofo/f1/linkdrop/lib/oauth/openidconsumer.py", line 323, in verify
    info = oidconsumer.complete(request.params, return_to)
  File "build/bdist.macosx-10.6-universal/egg/openid/consumer/consumer.py", line 414, in complete
    response = self.consumer.complete(message, endpoint, current_url)
  File "/Users/shanec/mofo/f1/linkdrop/lib/oauth/google_.py", line 99, in complete
    _, services = self._discover(claimed_id)
  File "build/bdist.macosx-10.6-universal/egg/openid/consumer/discover.py", line 470, in discover
    return discoverURI(identifier)
  File "build/bdist.macosx-10.6-universal/egg/openid/consumer/discover.py", line 462, in discoverURI
    claimed_id, openid_services = discoverYadis(uri)
  File "build/bdist.macosx-10.6-universal/egg/openid/consumer/discover.py", line 389, in discoverYadis
    response = yadisDiscover(uri)
  File "build/bdist.macosx-10.6-universal/egg/openid/yadis/discover.py", line 70, in discover
    resp = fetchers.fetch(uri, headers={'Accept': YADIS_ACCEPT_HEADER})
  File "build/bdist.macosx-10.6-universal/egg/openid/fetchers.py", line 42, in fetch
    return fetcher.fetch(url, body, headers)
  File "build/bdist.macosx-10.6-universal/egg/openid/fetchers.py", line 181, in fetch
    raise HTTPFetchingError(why=exc_inst)
HTTPFetchingError: urlopen error [Errno 67] request timed out

</pre>

**Comment by clarkbw** [comment]
server issue moved to: https://bugzilla.mozilla.org/show_bug.cgi?id=642917
client issue moved to: https://bugzilla.mozilla.org/show_bug.cgi?id=642918
