### ISSUE TITLE
bit.ly unicode error

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#74]
[Fri Mar 11 10:16:11 2011] [error] Traceback (most recent call last):

[Fri Mar 11 10:16:11 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/helpers.py", line 128, in json_exception_response

[Fri Mar 11 10:16:11 2011] [error]     return func(_args, *_kwargs)

[Fri Mar 11 10:16:11 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/controllers/send.py", line 168, in send

[Fri Mar 11 10:16:11 2011] [error]     shorturl = shorten_link(longurl)

[Fri Mar 11 10:16:11 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/shortener.py", line 36, in shorten_link

[Fri Mar 11 10:16:11 2011] [error]     bitly_result = urllib.urlopen("http://api.bit.ly/v3/shorten?login=%(bitly_userid)s&apiKey=%(bitly_key)s&longUrl=%(longUrl)s&format=json" % locals()).read()

[Fri Mar 11 10:16:11 2011] [error]   File "/usr/lib64/python2.6/urllib.py", line 86, in urlopen

[Fri Mar 11 10:16:11 2011] [error]     return opener.open(url)

[Fri Mar 11 10:16:11 2011] [error]   File "/usr/lib64/python2.6/urllib.py", line 177, in open

[Fri Mar 11 10:16:11 2011] [error]     fullurl = unwrap(toBytes(fullurl))

[Fri Mar 11 10:16:11 2011] [error]   File "/usr/lib64/python2.6/urllib.py", line 1027, in toBytes

[Fri Mar 11 10:16:11 2011] [error]     " contains non-ASCII characters")

[Fri Mar 11 10:16:11 2011] [error] UnicodeError: URL u'http://api.bit.ly/v3/shorten?login=XXX&apiKey=XXX&longUrl=http://www1.la.dell.com/br/pt/domesticos/Port\\xe1teis/inspiron-duo/pd.aspx?refid=inspiron-duo&amp;cs=brdhs1&amp;s=dhs&format=json' contains non-ASCII characters

**Comment by mixedpuppy** [comment]
fixed
