### ISSUE TITLE
yahoo error handling

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#75]
missing the to field:

[Fri Mar 11 12:25:41 2011] [error] Traceback (most recent call last):

[Fri Mar 11 12:25:41 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/helpers.py", line 128, in json_exception_response

[Fri Mar 11 12:25:41 2011] [error]     return func(_args, *_kwargs)

[Fri Mar 11 12:25:41 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/controllers/send.py", line 177, in send

[Fri Mar 11 12:25:41 2011] [error]     result, error = provider.api(acct).sendmessage(message, args)

[Fri Mar 11 12:25:41 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/yahoo_.py", line 204, in sendmessage

[Fri Mar 11 12:25:41 2011] [error]     to_addrs = AddressList(options['to'])

[Fri Mar 11 12:25:41 2011] [error]   File "build/bdist.linux-x86_64/egg/webob/multidict.py", line 307, in **getitem**

[Fri Mar 11 12:25:41 2011] [error]     return self._decode_value(self.multi.__getitem__(self._encode_key(key)))

[Fri Mar 11 12:25:41 2011] [error]   File "build/bdist.linux-x86_64/egg/webob/multidict.py", line 75, in **getitem**

[Fri Mar 11 12:25:41 2011] [error]     raise KeyError(key)

[Fri Mar 11 12:25:41 2011] [error] KeyError: 'to'

**Comment by mixedpuppy** [comment]
fixed
