### ISSUE TITLE
bit.ly error

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#79]
[Sat Mar 12 08:12:58 2011] [error] 08:12:58,852 ERROR [**name**] [Dummy-2] unexpected bitly response: '{ "data": [ ], "status_code": 500, "status_txt": "UNKNOWN_ERROR" }'

[Sat Mar 12 08:12:58 2011] [error] 08:12:58,853 ERROR [linkdrop.lib.helpers] [Dummy-2] <function send at 0x2b3a6f45ede8>((<linkdrop.controllers.send.SendController object at 0x2b3a6f689c10>,), {}) failed

[Sat Mar 12 08:12:58 2011] [error] Traceback (most recent call last):

[Sat Mar 12 08:12:58 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/helpers.py", line 128, in json_exception_response

[Sat Mar 12 08:12:58 2011] [error]     return func(_args, *_kwargs)

[Sat Mar 12 08:12:58 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/controllers/send.py", line 168, in send

[Sat Mar 12 08:12:58 2011] [error]     shorturl = shorten_link(longurl)

[Sat Mar 12 08:12:58 2011] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/shortener.py", line 46, in shorten_link

[Sat Mar 12 08:12:58 2011] [error]     return bitly_data["url"]

[Sat Mar 12 08:12:58 2011] [error] TypeError: list indices must be integers, not str

[Sat Mar 12 08:12:58 2011] [error] 08:12:58,853 INFO  [linkdrop-metrics] [Dummy-2] function='send' id='unhandled-exception' when=1299946378.8537171 remote_address='' error='TypeError'

**Comment by mixedpuppy** [comment]
fixed
