### ISSUE TITLE
fix logging of a redirect

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/f1#9]
<pre>

[Thu Nov 11 06:50:11 2010] [error] Traceback (most recent call last):
[Thu Nov 11 06:50:11 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/controllers/account.py", line 119, in verify
[Thu Nov 11 06:50:11 2010] [error]     user = auth.verify()
[Thu Nov 11 06:50:11 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/openidconsumer.py", line 324, in verify
[Thu Nov 11 06:50:11 2010] [error]     raise Exception("consumer canceled: "+info.message)
[Thu Nov 11 06:50:11 2010] [error] AttributeError: 'CancelResponse' object has no attribute 'message'
[Thu Nov 11 06:52:59 2010] [error] No handlers could be found for logger "linkdrop.lib.helpers"
[Thu Nov 11 06:54:21 2010] [error] Traceback (most recent call last):
[Thu Nov 11 06:54:21 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/controllers/account.py", line 119, in verify
[Thu Nov 11 06:54:21 2010] [error]     user = auth.verify()
[Thu Nov 11 06:54:21 2010] [error]   File "/home/linkdrop/linkdrop/linkdrop/lib/oauth/base.py", line 85, in verify
[Thu Nov 11 06:54:21 2010] [error]     redirect(session.get('end_point_auth_failure',self.config.get('oauth_failure')))
[Thu Nov 11 06:54:21 2010] [error]   File "/home/linkdrop/linkdrop-env/lib/python2.6/site-packages/Pylons-1.0-py2.6.egg/pylons/controllers/util.py", line 208, in redirect
[Thu Nov 11 06:54:21 2010] [error]     raise exc(location=url).exception
[Thu Nov 11 06:54:21 2010] [error] HTTPFound: 302 Found
[Thu Nov 11 06:54:21 2010] [error] Content-Type: text/html; charset=UTF-8
[Thu Nov 11 06:54:21 2010] [error] Content-Length: 0
[Thu Nov 11 06:54:21 2010] [error] Location: /auth.html#oauth_failure

</pre>

**Comment by mixedpuppy** [comment]
fixed 3e86e0482bd3ff91f578
